# Generated by Django 4.2.5 on 2025-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobportal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapedjob",
            name="company_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="employment_type",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="job_title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="keyword",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="location",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="platform",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="remote_option",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="scrapedjob",
            name="seniority_level",
            field=models.CharField(max_length=500),
        ),
    ]
