# Generated by Django 4.2.5 on 2025-05-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobportal", "0002_alter_scrapedjob_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapedjob",
            name="job_url",
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
