# Generated by Django 4.2.5 on 2025-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobportal", "0003_alter_scrapedjob_job_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapedjob",
            name="posted_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
